[build-system]
requires = ["setuptools", "cython", "wheel", "numpy"]
build-backend = "setuptools.build_meta"

[project]
name = "MDL-Density-Histogram"
version = "0.1.2"
description = "Cython-accelerated MDL histogram density estimation with dynamic programming, implementing Kontkanen & Myllymaki's algorithm (JMLR 2007)."
authors = [
    {name = "Götz Grimmer", email = "goetz-dev@web.de"}
]
license = {text = "Apache-2.0"}
readme = "README.md"


[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools]
package-dir = {"" = "src"}
